"""
Build a single-file, shareable VAT_Compliance_App_V7.pyw
==========================================================
VAT_Compliance_App_V6.pyw normally lives alongside five sibling modules
(app_theme.py, vat_returns_page.py, vat_reconciliation_core.py,
vat_source_loader.py, vat_summary_template_data.py) plus a logo.png file -
the right shape for maintenance, but it means sharing the app with the team
requires copying the whole folder.

This script bundles every module - and the logo - into one self-contained
.pyw that can be emailed or copied on its own. The modular sources stay the
master copy; the bundle is a build artefact, so **edit the modules and
re-run this script** rather than editing the generated file.

Uses the same technique as build_single_file.py: each module's source is
embedded as base64 and executed into a real module object registered in
sys.modules, so the app body's own `from app_theme import ...` /
`from vat_returns_page import ...` keep working untouched. The rest of
VAT_Compliance_App_V6.pyw's source (its own imports plus every class and
function) is appended to the generated file exactly as written - it is not
an importable module here, just the entry-point body - with one targeted
text substitution: `_EMBEDDED_LOGO_B64 = None` becomes the real base64 logo,
so load_sidebar_logo() finds it without needing logo.png on disk.

Run:
    python tools/build_single_file_v6.py
"""

import base64
import os
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
APP_DIR = os.path.dirname(HERE)
SOURCE_APP = os.path.join(APP_DIR, "VAT_Compliance_App_V6.pyw")
OUTPUT = os.path.join(APP_DIR, "VAT_Compliance_App_V7.pyw")
LOGO_PATH = os.path.join(APP_DIR, "logo.png")

# Dependency order: each module is executed after the ones it imports.
MODULES = [
    "vat_summary_template_data",
    "vat_source_loader",
    "vat_reconciliation_core",
    "app_theme",
    "vat_returns_page",
]

# The exact line in VAT_Compliance_App_V6.pyw that gets replaced with the
# real base64 logo. Must appear exactly once - see load_sidebar_logo()'s
# docstring in that file for why this hook exists.
LOGO_HOOK = "_EMBEDDED_LOGO_B64 = None"

HEADER = '''"""
VAT Compliance Automation - single-file edition (V7)
=====================================================
Everything the app needs - every page, the VAT-Returns/Spain reconciliation
tool, and the company logo - is inside this one file. Double-click to run
(the .pyw extension launches it without a console window).

Requires Python with these packages installed:
    pip install pandas openpyxl requests requests-ntlm urllib3 xlrd

Optional (for a sharper sidebar logo - the app runs fine without it, the
logo just falls back to a coarser resize):
    pip install Pillow

DO NOT EDIT THIS FILE - it is generated. The maintained source is
VAT_Compliance_App_V6.pyw and its sibling modules; rebuild this file with:
    python tools/build_single_file_v6.py
"""

import base64
import importlib
import os
import site
import sys
import tkinter as tk
import types
from tkinter import messagebox

# Third-party packages required to run, mapped to their pip install name.
# numpy is listed explicitly even though no module here imports it directly -
# pandas depends on it, and a machine where it's missing or broken otherwise
# only surfaces that as a raw ImportError once pandas itself is loaded.
# (Pillow is intentionally not required - see load_sidebar_logo() below,
# which already falls back gracefully when it's missing.)
REQUIRED_PACKAGES = {
    "numpy": "numpy",
    "pandas": "pandas",
    "openpyxl": "openpyxl",
    "requests": "requests",
    "requests_ntlm": "requests-ntlm",
    "urllib3": "urllib3",
    "xlrd": "xlrd",
}

# Module sources, base64-encoded, in the order they must be executed.
_MODULE_ORDER = %(order)r
_MODULE_SOURCES = {
%(sources)s}


def _install_modules():
    """Execute the embedded modules and register them in sys.modules.

    Registering real module objects (rather than exec'ing everything into one
    namespace) keeps the app body's `from app_theme import ...` / `from
    vat_returns_page import ...` style imports working exactly as they do in
    the unbundled application.
    """
    for name in _MODULE_ORDER:
        if name in sys.modules:
            continue
        source = base64.b64decode(_MODULE_SOURCES[name]).decode("utf-8")
        module = types.ModuleType(name)
        module.__file__ = f"<embedded {name}.py>"
        sys.modules[name] = module
        try:
            exec(compile(source, module.__file__, "exec"), module.__dict__)
        except Exception:
            # Do not leave a half-initialised module behind for a later
            # import to pick up and fail on more confusingly.
            del sys.modules[name]
            raise


def _show_error(title, message):
    root = tk.Tk()
    root.withdraw()
    messagebox.showerror(title, message)
    root.destroy()


def _import_failures():
    """(install_name, "ExceptionType: message") for each required package
    that fails to import - not just a bare "missing" label. A package can be
    on disk and still fail to import for reasons that have nothing to do
    with installation (a broken DLL, an ABI mismatch between numpy/pandas
    builds, antivirus quarantine, ...) - swallowing the real exception hides
    exactly the information needed to tell "not installed" apart from
    "installed but broken", which is the difference that matters once the
    obvious causes (wrong interpreter, PYTHONNOUSERSITE) are ruled out."""
    failures = []
    for module, install in REQUIRED_PACKAGES.items():
        try:
            importlib.import_module(module)
        except Exception as exc:
            failures.append((install, f"{type(exc).__name__}: {exc}"))
    return failures


def _user_site_diagnostics():
    """Explains the "pip says installed, app says missing" case: packages
    installed with `pip install --user` only work if the interpreter's user
    site-packages directory is enabled and actually on sys.path. Corporate
    machines commonly set PYTHONNOUSERSITE, which silently disables it -
    pip doesn't check that variable, only Python's import machinery does."""
    lines = [f"site.ENABLE_USER_SITE: {site.ENABLE_USER_SITE}"]
    try:
        user_site = site.getusersitepackages()
        lines.append(f"user site-packages: {user_site} (exists: {os.path.isdir(user_site)})")
    except Exception as exc:
        lines.append(f"user site-packages: could not determine ({exc})")
    lines.append(f"PYTHONNOUSERSITE env var: {os.environ.get('PYTHONNOUSERSITE')!r}")
    return "\\n".join(f"    {line}" for line in lines)


_failures = _import_failures()
if _failures:
    _missing = [name for name, _ in _failures]
    # Naming the exact interpreter matters: on a machine with more than one
    # Python installed, "pip install" and this app can silently resolve to
    # different ones - `pip` reports success while this dialog still shows,
    # because the packages went into a different interpreter's site-packages
    # than the one that opened this file. Showing sys.executable turns that
    # from a confusing back-and-forth into a one-line fix. The user-site
    # diagnostics cover the *same-interpreter* variant of this problem,
    # where `pip install --user` genuinely wrote to the right place but the
    # running app still can't see it (PYTHONNOUSERSITE or elevation). The
    # per-package error text below covers everything else - a package can
    # be correctly installed and still fail to import for reasons "pip
    # install" won't fix at all (broken DLL, numpy/pandas ABI mismatch,
    # antivirus quarantine, ...).
    _show_error(
        "Missing Python packages",
        "These Python packages could not be imported:\\n\\n"
        + "\\n".join(f"    {name}: {err}" for name, err in _failures)
        + "\\n\\nThis app is running under:\\n\\n"
        f"    {sys.executable}\\n"
        f"    Python {sys.version.split()[0]}\\n\\n"
        "If 'pip install' already reports these as satisfied, check "
        "whether your user site-packages is actually visible to this "
        "interpreter:\\n\\n"
        + _user_site_diagnostics()
        + "\\n\\nIf the error above is something other than "
        "'ModuleNotFoundError' (e.g. a DLL load failure or a version "
        "conflict), reinstalling won't fix it by itself - the exact error "
        "text is the real clue and is worth sharing as-is when asking for "
        "help.\\n\\nTo reinstall for THIS interpreter anyway, run this "
        "exact command at a command prompt (important if more than one "
        "Python is installed - plain 'pip install' can target a different "
        "one):\\n\\n"
        f'    "{sys.executable}" -m pip install --force-reinstall {" ".join(_missing)}\\n\\n'
        "If that still doesn't work, run the same command from an "
        "Administrator command prompt to install system-wide instead of to "
        "your user site-packages - that sidesteps PYTHONNOUSERSITE/"
        "elevation issues entirely.",
    )
    sys.exit(1)

try:
    _install_modules()
except Exception as _exc:
    _show_error(
        "Could not start",
        f"The application failed to load:\\n\\n{type(_exc).__name__}: {_exc}",
    )
    sys.exit(1)


# ════════════════════════════════════════════════════════════
#  Application body - VAT_Compliance_App_V6.pyw, unmodified below this
#  point except for the embedded-logo substitution noted in its own source.
# ════════════════════════════════════════════════════════════

%(app_body)s
'''


def _wrap_b64(blob):
    lines = textwrap.wrap(blob, 96)
    return "\n".join(f'        "{line}"' for line in lines)


def encode_module(name):
    path = os.path.join(APP_DIR, f"{name}.py")
    with open(path, "rb") as fh:
        blob = base64.b64encode(fh.read()).decode("ascii")
    return f'    "{name}": (\n{_wrap_b64(blob)}\n    ),\n', os.path.getsize(path)


def encode_logo():
    with open(LOGO_PATH, "rb") as fh:
        blob = base64.b64encode(fh.read()).decode("ascii")
    lines = textwrap.wrap(blob, 96)
    literal = " \\\n".join(f'"{line}"' for line in lines)
    return literal, os.path.getsize(LOGO_PATH)


def main():
    if not os.path.exists(LOGO_PATH):
        raise SystemExit(f"logo.png not found at {LOGO_PATH} - place it there before building.")

    chunks = []
    total_src = 0
    for name in MODULES:
        chunk, size = encode_module(name)
        chunks.append(chunk)
        total_src += size
        print(f"  embedded {name}.py ({size:,} bytes)")

    logo_literal, logo_size = encode_logo()
    print(f"  embedded logo.png ({logo_size:,} bytes)")

    with open(SOURCE_APP, "r", encoding="utf-8") as fh:
        app_body = fh.read()

    hits = app_body.count(LOGO_HOOK)
    if hits != 1:
        raise SystemExit(
            f"Expected exactly one '{LOGO_HOOK}' line in {SOURCE_APP}, found {hits}. "
            "The logo-embedding hook may have been edited or removed - fix that before rebuilding."
        )
    app_body = app_body.replace(LOGO_HOOK, f"_EMBEDDED_LOGO_B64 = ({logo_literal})")

    text = HEADER % {"order": MODULES, "sources": "".join(chunks), "app_body": app_body}
    with open(OUTPUT, "w", encoding="utf-8") as fh:
        fh.write(text)

    print(f"\nWrote {OUTPUT}")
    print(f"  {len(MODULES)} module(s) + logo, {total_src + logo_size:,} bytes of source/assets "
          f"-> {os.path.getsize(OUTPUT):,} bytes single file")


if __name__ == "__main__":
    main()
