"""
Build a single-file, shareable VAT_Reconciliation_Standalone.pyw
================================================================
The application normally lives in four modules plus a launcher. That is the
right shape for maintenance - and for dropping the tab into the main desktop
app - but it means sharing the tool requires copying the whole folder, and
copying only the launcher produces a confusing "no module named ..." error.

This script bundles every module into one self-contained .pyw that can be
emailed or copied on its own. The modular sources stay the master copy; the
bundle is a build artefact, so **edit the modules and re-run this script**
rather than editing the generated file.

Each module's source is embedded as base64 and executed into a real module
object registered in sys.modules, so the cross-module imports
(`from vat_source_loader import ...`) keep working untouched. Base64 avoids
having to escape the quotes and backslashes in the original sources.

Run:
    python tools/build_single_file.py
"""

import base64
import os
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
APP_DIR = os.path.dirname(HERE)
OUTPUT = os.path.join(APP_DIR, "VAT_Reconciliation_Standalone.pyw")

# Dependency order: each module is executed after the ones it imports.
MODULES = [
    "vat_summary_template_data",
    "vat_source_loader",
    "vat_reconciliation_core",
    "vat_reconciliation_tab",
]

HEADER = '''"""
VAT Reconciliation - single-file edition
=======================================
Everything the tool needs is inside this one file. Double-click to run (the
.pyw extension launches it without a console window).

Requires Python with these packages installed:
    pip install pandas openpyxl requests xlrd

DO NOT EDIT THIS FILE - it is generated. The maintained source is the set of
modules in the application folder; rebuild this file with:
    python tools/build_single_file.py
"""

import base64
import importlib
import os
import site
import sys
import tkinter as tk
import types
from tkinter import messagebox, ttk

# Third-party packages, mapped to the name used to install them.
# numpy is listed explicitly even though no module here imports it directly -
# pandas depends on it, and a machine where it's missing or broken otherwise
# only surfaces that as a raw ImportError once pandas itself is loaded.
REQUIRED_PACKAGES = {
    "numpy": "numpy",
    "pandas": "pandas",
    "openpyxl": "openpyxl",
    "requests": "requests",
    "xlrd": "xlrd",
}

# Module sources, base64-encoded, in the order they must be executed.
_MODULE_ORDER = %(order)r
_MODULE_SOURCES = {
%(sources)s}


def _install_modules():
    """Execute the embedded modules and register them in sys.modules.

    Registering real module objects (rather than exec'ing everything into one
    namespace) keeps the original `from vat_source_loader import ...` style
    imports working exactly as they do in the unbundled application.
    """
    for name in _MODULE_ORDER:
        if name in sys.modules:
            continue
        source = base64.b64decode(_MODULE_SOURCES[name]).decode("utf-8")
        module = types.ModuleType(name)
        module.__file__ = f"<embedded {name}.py>"
        sys.modules[name] = module
        try:
            exec(compile(source, module.__file__, "exec"), module.__dict__)
        except Exception:
            # Do not leave a half-initialised module behind for a later import
            # to pick up and fail on more confusingly.
            del sys.modules[name]
            raise


def _show_error(title, message):
    root = tk.Tk()
    root.withdraw()
    messagebox.showerror(title, message)
    root.destroy()


def _import_failures():
    """(install_name, "ExceptionType: message") for each required package
    that fails to import - not just a bare "missing" label. A package can be
    on disk and still fail to import for reasons that have nothing to do
    with installation (a broken DLL, an ABI mismatch between numpy/pandas
    builds, antivirus quarantine, ...) - swallowing the real exception hides
    exactly the information needed to tell "not installed" apart from
    "installed but broken", which is the difference that matters once the
    obvious causes (wrong interpreter, PYTHONNOUSERSITE) are ruled out."""
    failures = []
    for module, install in REQUIRED_PACKAGES.items():
        try:
            importlib.import_module(module)
        except Exception as exc:
            failures.append((install, f"{type(exc).__name__}: {exc}"))
    return failures


def _user_site_diagnostics():
    """Explains the "pip says installed, app says missing" case: packages
    installed with `pip install --user` only work if the interpreter's user
    site-packages directory is enabled and actually on sys.path. Corporate
    machines commonly set PYTHONNOUSERSITE, which silently disables it -
    pip doesn't check that variable, only Python's import machinery does."""
    lines = [f"site.ENABLE_USER_SITE: {site.ENABLE_USER_SITE}"]
    try:
        user_site = site.getusersitepackages()
        lines.append(f"user site-packages: {user_site} (exists: {os.path.isdir(user_site)})")
    except Exception as exc:
        lines.append(f"user site-packages: could not determine ({exc})")
    lines.append(f"PYTHONNOUSERSITE env var: {os.environ.get('PYTHONNOUSERSITE')!r}")
    return "\\n".join(f"    {line}" for line in lines)


def main():
    failures = _import_failures()
    if failures:
        missing = [name for name, _ in failures]
        # Naming the exact interpreter matters: on a machine with more than
        # one Python installed, "pip install" and this app can silently
        # resolve to different ones - `pip` reports success while this
        # dialog still shows, because the packages went into a different
        # interpreter's site-packages than the one that opened this file.
        # Showing sys.executable turns that from a confusing back-and-forth
        # into a one-line fix. The user-site diagnostics cover the
        # *same-interpreter* variant of this problem, where
        # `pip install --user` genuinely wrote to the right place but the
        # running app still can't see it (PYTHONNOUSERSITE or elevation).
        # The per-package error text below covers everything else - a
        # package can be correctly installed and still fail to import for
        # reasons "pip install" won't fix at all (broken DLL, numpy/pandas
        # ABI mismatch, antivirus quarantine, ...).
        _show_error(
            "Missing Python packages",
            "These Python packages could not be imported:\\n\\n"
            + "\\n".join(f"    {name}: {err}" for name, err in failures)
            + "\\n\\nThis app is running under:\\n\\n"
            f"    {sys.executable}\\n"
            f"    Python {sys.version.split()[0]}\\n\\n"
            "If 'pip install' already reports these as satisfied, check "
            "whether your user site-packages is actually visible to this "
            "interpreter:\\n\\n"
            + _user_site_diagnostics()
            + "\\n\\nIf the error above is something other than "
            "'ModuleNotFoundError' (e.g. a DLL load failure or a version "
            "conflict), reinstalling won't fix it by itself - the exact "
            "error text is the real clue and is worth sharing as-is when "
            "asking for help.\\n\\nTo reinstall for THIS interpreter "
            "anyway, run this exact command at a command prompt (important "
            "if more than one Python is installed - plain 'pip install' "
            "can target a different one):\\n\\n"
            f'    "{sys.executable}" -m pip install --force-reinstall {" ".join(missing)}\\n\\n'
            "If that still doesn't work, run the same command from an "
            "Administrator command prompt to install system-wide instead "
            "of to your user site-packages - that sidesteps "
            "PYTHONNOUSERSITE/elevation issues entirely.",
        )
        return

    try:
        _install_modules()
        from vat_reconciliation_tab import VatReconciliationTab
    except Exception as exc:
        _show_error(
            "Could not start",
            f"The application failed to load:\\n\\n{type(exc).__name__}: {exc}",
        )
        return

    root = tk.Tk()
    root.title("VAT Reconciliation")
    root.geometry("880x620")
    root.minsize(720, 520)

    notebook = ttk.Notebook(root)
    notebook.pack(fill="both", expand=True, padx=6, pady=6)
    notebook.add(VatReconciliationTab(notebook), text="VAT Reconciliation")

    root.mainloop()


if __name__ == "__main__":
    main()
'''


def encode_module(name):
    path = os.path.join(APP_DIR, f"{name}.py")
    with open(path, "rb") as fh:
        blob = base64.b64encode(fh.read()).decode("ascii")
    lines = textwrap.wrap(blob, 96)
    body = "\n".join(f'        "{line}"' for line in lines)
    return f'    "{name}": (\n{body}\n    ),\n', os.path.getsize(path)


def main():
    chunks = []
    total_src = 0
    for name in MODULES:
        chunk, size = encode_module(name)
        chunks.append(chunk)
        total_src += size
        print(f"  embedded {name}.py ({size:,} bytes)")

    text = HEADER % {"order": MODULES, "sources": "".join(chunks)}
    with open(OUTPUT, "w", encoding="utf-8") as fh:
        fh.write(text)

    print(f"\nWrote {OUTPUT}")
    print(f"  {len(MODULES)} modules, {total_src:,} bytes of source "
          f"-> {os.path.getsize(OUTPUT):,} bytes single file")


if __name__ == "__main__":
    main()
