"""
Build a single-file, shareable VAT_Reconciliation_Standalone.pyw
================================================================
The application normally lives in four modules plus a launcher. That is the
right shape for maintenance - and for dropping the tab into the main desktop
app - but it means sharing the tool requires copying the whole folder, and
copying only the launcher produces a confusing "no module named ..." error.

This script bundles every module into one self-contained .pyw that can be
emailed or copied on its own. The modular sources stay the master copy; the
bundle is a build artefact, so **edit the modules and re-run this script**
rather than editing the generated file.

Each module's source is embedded as base64 and executed into a real module
object registered in sys.modules, so the cross-module imports
(`from vat_source_loader import ...`) keep working untouched. Base64 avoids
having to escape the quotes and backslashes in the original sources.

Run:
    python tools/build_single_file.py
"""

import base64
import os
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
APP_DIR = os.path.dirname(HERE)
OUTPUT = os.path.join(APP_DIR, "VAT_Reconciliation_Standalone.pyw")

# Dependency order: each module is executed after the ones it imports.
MODULES = [
    "vat_summary_template_data",
    "vat_source_loader",
    "vat_reconciliation_core",
    "vat_reconciliation_tab",
]

HEADER = '''"""
VAT Reconciliation - single-file edition
=======================================
Everything the tool needs is inside this one file. Double-click to run (the
.pyw extension launches it without a console window).

Requires Python with these packages installed:
    pip install pandas openpyxl requests xlrd

DO NOT EDIT THIS FILE - it is generated. The maintained source is the set of
modules in the application folder; rebuild this file with:
    python tools/build_single_file.py
"""

import base64
import importlib.util
import os
import sys
import tkinter as tk
import types
from tkinter import messagebox, ttk

# Third-party packages, mapped to the name used to install them.
REQUIRED_PACKAGES = {
    "pandas": "pandas",
    "openpyxl": "openpyxl",
    "requests": "requests",
    "xlrd": "xlrd",
}

# Module sources, base64-encoded, in the order they must be executed.
_MODULE_ORDER = %(order)r
_MODULE_SOURCES = {
%(sources)s}


def _install_modules():
    """Execute the embedded modules and register them in sys.modules.

    Registering real module objects (rather than exec'ing everything into one
    namespace) keeps the original `from vat_source_loader import ...` style
    imports working exactly as they do in the unbundled application.
    """
    for name in _MODULE_ORDER:
        if name in sys.modules:
            continue
        source = base64.b64decode(_MODULE_SOURCES[name]).decode("utf-8")
        module = types.ModuleType(name)
        module.__file__ = f"<embedded {name}.py>"
        sys.modules[name] = module
        try:
            exec(compile(source, module.__file__, "exec"), module.__dict__)
        except Exception:
            # Do not leave a half-initialised module behind for a later import
            # to pick up and fail on more confusingly.
            del sys.modules[name]
            raise


def _show_error(title, message):
    root = tk.Tk()
    root.withdraw()
    messagebox.showerror(title, message)
    root.destroy()


def _missing_packages():
    return [install for module, install in REQUIRED_PACKAGES.items()
            if importlib.util.find_spec(module) is None]


def main():
    missing = _missing_packages()
    if missing:
        _show_error(
            "Missing Python packages",
            "These Python packages need to be installed:\\n\\n"
            + "\\n".join(f"    {name}" for name in missing)
            + "\\n\\nInstall them by running this at a command prompt:\\n\\n"
            f"    pip install {' '.join(missing)}",
        )
        return

    try:
        _install_modules()
        from vat_reconciliation_tab import VatReconciliationTab
    except Exception as exc:
        _show_error(
            "Could not start",
            f"The application failed to load:\\n\\n{type(exc).__name__}: {exc}",
        )
        return

    root = tk.Tk()
    root.title("VAT Reconciliation")
    root.geometry("880x620")
    root.minsize(720, 520)

    notebook = ttk.Notebook(root)
    notebook.pack(fill="both", expand=True, padx=6, pady=6)
    notebook.add(VatReconciliationTab(notebook), text="VAT Reconciliation")

    root.mainloop()


if __name__ == "__main__":
    main()
'''


def encode_module(name):
    path = os.path.join(APP_DIR, f"{name}.py")
    with open(path, "rb") as fh:
        blob = base64.b64encode(fh.read()).decode("ascii")
    lines = textwrap.wrap(blob, 96)
    body = "\n".join(f'        "{line}"' for line in lines)
    return f'    "{name}": (\n{body}\n    ),\n', os.path.getsize(path)


def main():
    chunks = []
    total_src = 0
    for name in MODULES:
        chunk, size = encode_module(name)
        chunks.append(chunk)
        total_src += size
        print(f"  embedded {name}.py ({size:,} bytes)")

    text = HEADER % {"order": MODULES, "sources": "".join(chunks)}
    with open(OUTPUT, "w", encoding="utf-8") as fh:
        fh.write(text)

    print(f"\nWrote {OUTPUT}")
    print(f"  {len(MODULES)} modules, {total_src:,} bytes of source "
          f"-> {os.path.getsize(OUTPUT):,} bytes single file")


if __name__ == "__main__":
    main()
